#logging:
#  level:
#    ROOT: info
#    org.hibernate.SQL: INFO
#    ma.Anafal_Dahhaniback: INFO
#
#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/Airbnb
#    username: postgres
#    password: Admin
#  jpa:
#    properties:
#      hibernate:
#        default_schema: airbnb_clone
##  liquibase:
##    contexts: prod
##    default-schema: airbnb_clone

logging:
  level:
    ROOT: INFO
    org.hibernate.SQL: INFO
    ma.Anafal_Dahhaniback: INFO

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/airbnb?serverTimezone=UTC
    username: root  # Replace with your MySQL username
    password:   # Replace with your MySQL password
    driver-class-name: com.mysql.cj.jdbc.Driver  # MySQL driver class
  jpa:
    properties:
      hibernate:
        ddl-auto: none
#  liquibase:
#    contexts: prod
#    default-schema: airbnb_clone
